export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const SIGN_OUT = 'SIGN_OUT';

export const ROUTING_TO_PAGE = 'ROUTING_TO_PAGE';
export const REDIRECT_TO_SIGN_IN = 'REDIRECT_TO_SIGN_IN';
export const REDIRECT_TO_MAIN = 'REDIRECT_TO_MAIN';

export const FETCH_ORDER_REQUESTED = 'FETCH_ORDER_FAILURE';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const FETCH_OFFER_REQUESTED = 'FETCH_OFFER_FAILURE';
export const FETCH_OFFER_SUCCESS = 'FETCH_OFFER_SUCCESS';
export const FETCH_OFFER_FAILURE = 'FETCH_OFFER_FAILURE';
